name: Run flashcards script

on:
  schedule:
    - cron: "0 6-22/2 * * *"
  workflow_dispatch:

permissions:
  contents: write  # serve per fare il commit automatico

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flashcards script
        run: python3 flashcards_video.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add flashcards.csv
          git commit -m "Update flashcards CSV automatically" || echo "No changes to commit"
          git push
